### ISSUE TITLE
[SUGGESTION] Update Inventory Sorter and enabled by default

### ISSUE THREAD

**Issue by Dinip** [Gogo08190/chroma-endless-2#1]
### Description of Suggestion

Please consider updating Inventory Sorter to the beta version [inventorysorter-1.18.2-19.0.4.jar](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter/files/4055080), which solves the conflict with middle click for sorting the inventory and to change the item amount of items in the pattern terminal. Also fixes when there is a craftable item in the system, that already has some amount of items stored, but want to craft more, which also uses middle click.

Also revert inventory sorter and inventory essentials to "required: true" on the manifest, which are 2 important, mods, that were changed in the last patch (1.0.6) to come disabled by default.

### How does this improve the experience?

There isn't much more to say, updating Inventory Sorter solves the issue with middle click conflict between AE2 e Inventory Sorter, that for now, need to be changed (inventory sort key) to another key/button, since from the AE2 side, it is not remappable.
Reverting both mods to "required: true" brings back QoL for all the players, that got they inventory sorter/helper disabled in the last update.

### Screenshots

![image](https://github.com/Gogo08190/chroma-endless-2/assets/8941012/0a125318-56c1-4706-9266-9bd621c1a713)

**Comment by Gogo08190** [comment]
Yes, it's planned to put them back in the next update.
