### ISSUE TITLE
[BUG] Framed drawers can't be customized

### ISSUE THREAD

**Issue by iglee42** [Gogo08190/chroma-endless-2#10]
### Description of the Bug

Framed drawers from functional storage can't be customized in a crafting table
I tried with different blocks but that didn't work

### Expected Behaviour

1. Place a framed drawer with block in a crafting table
2. Give a customized framed drawer

### Modpack Version

1.0.9HF

### Screenshots

![Capture d'écran 2024-04-04 184300](https://github.com/Gogo08190/chroma-endless-2/assets/50081542/b1aace4a-d17c-4cdd-a4cd-a0888c0a6c7c)

### Extra Info

I play on a dedicated server

**Comment by Gogo08190** [comment]
![image](https://github.com/Gogo08190/chroma-endless-2/assets/41335079/96d6b5b7-41c9-41dc-9795-2b39dfe09852)

**Comment by iglee42** [comment]
ok
