### ISSUE TITLE
Miss spelling

### ISSUE THREAD

**Issue by Reithsaw** [Gogo08190/chroma-endless-2#12]
In the quest " Construction Wands " you wrote " snealk + control "

![image](https://github.com/Gogo08190/chroma-endless-2/assets/51093339/4612726a-c8c4-40ea-8734-57a2736f9b17)

**Comment by Gogo08190** [comment]
Thanks for report, it will be [fixed](https://github.com/Gogo08190/chroma-endless-2/commit/565f0e8171cef7d2d587eadb4fe39f92074f2eb7) for the next update
