### ISSUE TITLE
[BUG] Time in a bottle crash on Mana and Artifice

### ISSUE THREAD

**Issue by Micaxs** [Gogo08190/chroma-endless-2#16]
### Description of the Bug

Server Crash with Time in a bottle on mana and artifice block.

### Expected Behaviour

Srsly.. Fix your pack so it doesn't crash server.

### Modpack Version

latest

### Log

https://mclo.gs/bgadnxg

**Comment by Micaxs** [comment]
Wdym not planned?

**Comment by Gogo08190** [comment]
First, "Srsly.. Fix your pack so it doesn't crash server." : You should have spoken to me better

And secondly, it's a problem from mna and TIAB, not a problem from the modpack so go complain to the modder about the mods in question.
