### ISSUE TITLE
Regulator Augment impossible crafting

### ISSUE THREAD

**Issue by Darcodo** [Gogo08190/chroma-endless-2#18]
![2024-05-11_10 27 55](https://github.com/Gogo08190/chroma-endless-2/assets/80262660/caa9cd3a-b250-48c1-aef2-dfc62e45df67)

![2024-05-11_10 27 51](https://github.com/Gogo08190/chroma-endless-2/assets/80262660/37901ed2-a53d-499b-8daf-955d33036747)
item which is to the left of augment core does not exist

**Comment by Gogo08190** [comment]
![image](https://github.com/Gogo08190/chroma-endless-2/assets/41335079/35f46813-c573-406f-b7b6-c82c87dd633e)

You have a problem with your modpack installation

**Comment by Darcodo** [comment]
I still don't understand I reinstalled the pack and restarted the server and I still have the same craft

**Comment by Darcodo** [comment]
I might be able to find where it comes from is "JustEnoughCalculation", it did not install server side even when reinstalling the modpack

**Comment by Gogo08190** [comment]
![image](https://github.com/Gogo08190/chroma-endless-2/assets/41335079/7997c461-634c-4789-b4da-6ee4db2a7385)
The mod is present in the serverfile

**Comment by Darcodo** [comment]
![Capture d’écran (45)](https://github.com/Gogo08190/chroma-endless-2/assets/80262660/2c39b3e8-f815-42ab-a066-16c376dae096)
this is what I have after re-installing the modpack

**Comment by Gogo08190** [comment]
In this case, add it manually
