### ISSUE TITLE
[BUG] Mana and artifice ritual not working because "incontrol" rules

### ISSUE THREAD

**Issue by Dinip** [Gogo08190/chroma-endless-2#2]
### Description of the Bug

Since the update for 1.0.7, it isn't possible to level up from tier 2 to 3, in mana and artifice, since it requires one of four rituals, that summons an entity, and that entity seems to be blocked by the change made [in this commit.](https://github.com/Gogo08190/chroma-endless-2/commit/d2a9179babf74a16d3f0a8d2f409dab5d615e8d8)

### Expected Behaviour

1. Prepare one of the four rituals from the following printscreen
2. Do the ritual
3. Ritual summons an entity
4. Complete the task

### Modpack Version

1.0.7

### Screenshots

![image](https://github.com/Gogo08190/chroma-endless-2/assets/8941012/f7396e5b-8356-4db8-a70e-b681a24f06c2)
![image](https://github.com/Gogo08190/chroma-endless-2/assets/8941012/1db2edf2-35a0-4be6-872a-edd577d4f7a8)

**Comment by Gogo08190** [comment]
you just need to activate the mana mobs. 

On my side the ritual work

**Comment by Gogo08190** [comment]
I tested and indeed in the mana quests you can activate or deactivate the mana mobs (last update). 

They must be activated for the rituals to work.

**Comment by Dinip** [comment]
Yeah, you are right. 
I was not aware of that we needed to toggle the mana and artifice mobs. It was a player on my server that raised the issue while trying to level up to tier 3, so I was not really that aware of that option.

**Comment by Gogo08190** [comment]
Some people were fed up with having lots of mana mobs around them and asked me to find a solution to have an option to disable mana mobs.
