### ISSUE TITLE
Unable to silk touch spawners

### ISSUE THREAD

**Issue by cauliflower69** [Gogo08190/chroma-endless-2#3]
### Description of the Bug

Unable to silk touch spawners using Tinkers and Minecraft enchanted silk touch pick

### Expected Behaviour

The spawner to drop. I have checked the server cfg and it is set to 

The level of silk touch needed to harvest a spawner.  Set to -1 to disable, 0 to always drop.  The enchantment module can increase the max level of silk touch. [range: -1 ~ 127, default: 1]
    I:"Spawner Silk Level"=1

### Modpack Version

1.0.7

**Comment by hugoduterque** [comment]
This is normal, we have disabled breaking spawners with silktouch. You have to go through the spirit mod.

**Comment by Gogo08190** [comment]
This is normal, we have disabled breaking spawners with silktouch. You have to go through the spirit mod.

**Comment by cauliflower69** [comment]
Thanks for the reply

**Comment by HikerL** [comment]
> This is normal, we have disabled breaking spawners with silktouch. You have to go through the spirit mod.

Is it fine and designed within expectation that we can use Cardboard Box from Mekanism mod to move the  spawners at Stage 3?

**Comment by cauliflower69** [comment]
> > This is normal, we have disabled breaking spawners with silktouch. You have to go through the spirit mod.
> 
> Is it fine and designed within expectation that we can use Cardboard Box from Mekanism mod to move the spawners at Stage 3?

You can do this in stage 2 with the Immersive Engineering sawmill
