### ISSUE TITLE
[BUG] *Replace with brief description of the issue*

### ISSUE THREAD

**Issue by Fabinico** [Gogo08190/chroma-endless-2#34]
### Description of the Bug

is it normal that the shard of creative is not displayed because you can't craft it

### Expected Behaviour

is it normal that the shard of creative is not displayed because you can't craft it

### Modpack Version

1.1.1

### Screenshots

https://github.com/user-attachments/assets/761ee590-492b-4a42-8856-db8cf1cb0666

**Comment by Gogo08190** [comment]
It's a quest reward "the millionaire"
