### ISSUE TITLE
[BUG] Can't find any Mineral Deposits in Blue Skies dimensions

### ISSUE THREAD

**Issue by HikerL** [Gogo08190/chroma-endless-2#4]
### Description of the Bug

I can't find any Mineral Deposits of Immersive Engineering mod such as "blue_skies:ores/falsite","blue_skies:ores/charoite" in Blue Skies dimensions 'blue_skies:everbright', and 'blue_skies:everdawn' as it has been written in 
 kubejs\server_scripts\pack\recipetypes\immersiveengineering\mineral.js .
Generation of the Deposits in Overworld and The Undergarden works fine. I haven't got to beyond_earth worlds.
So I want to know if it is designed to ban the deposits generation in Everbright and Everdawn world.

### Expected Behaviour

Some mineral deposits of Blue skies mod should be generated in Everbright and Everdawn.

### Modpack Version

1.0.7 and the first-time world generation in 1.0.7

### Screenshots

![ea77d451ab5e13df8c73f1330da325a](https://github.com/Gogo08190/chroma-endless-2/assets/35104870/b700c6a4-6524-4248-9810-20eafa301384)
The screenshots here is the Immer-Eng mod savedata of a new world, and I traveled through overworld ,Blue skies world and the Undergarden, the deposits generation works well except for Blue skies worlds. 

### Extra Info

Extra mods: ModernUI-Forge-1.18.2-3.9.0.1; 
                    Embeddium-0.2.17+mc1.18.2; 
                    Textrues_embeddium_options-0.1.1+mc1.18.2
these mods should have not affect the world generation.

**Comment by Gogo08190** [comment]
The Blue Skies ores will be removed from the immersive excavator for the next update, you can pass the drilling machine from Create or by botania or by industrial foregoing to get some in the next update.
