### ISSUE TITLE
[BUG] Missing recipe for Researching Table From Relics Mod

### ISSUE THREAD

**Issue by ChimeraGaming** [Gogo08190/chroma-endless-2#41]
### Description of the Bug

No Receipe, When instructed that the Recipe is and tried to craft manually:

Red Wool , Glowstone Block , Red Wool
x , Gold Block , x
any slab , any plank , any slab

is still doesn't work

### Expected Behaviour

crafted..

### Modpack Version

1.1.2

### Screenshots

![image](https://github.com/user-attachments/assets/5a060074-4ac6-4b5e-a927-8a8177bf0306)

**Comment by Gogo08190** [comment]
You can buy it in the shop
