### ISSUE TITLE
[BUG] Void Miner Tier 2 Structure inconsistency

### ISSUE THREAD

**Issue by fullsets92** [Gogo08190/chroma-endless-2#43]
### Description of the Bug

One of the 4 "legs" of  the structure is different

### Expected Behaviour

Considering the structure is otherwise symmetrical, i imagine all 4 legs should be the same.

### Modpack Version

1.1.2

### Screenshots

![2024-09-20_20 17 06](https://github.com/user-attachments/assets/43cac1e0-29fe-489c-b524-e63983f19f5f)

**Comment by Gogo08190** [comment]
Yes, someone has already reported this issue to me, but if I fix it, many people who have this multiblock will no longer be able to use it because the structure will no longer be correct.
