### ISSUE TITLE
[BUG?] create ore excavation- not infinite like the mod page says 

### ISSUE THREAD

**Issue by ChimeraGaming** [Gogo08190/chroma-endless-2#45]
### Description of the Bug

The stage 1 ores are not infinite (haven’t found others like diamond to test yet)

is this in intentionally set to be finite or is it a bug?
Because our copper one is only 387 in the chunk. Seems pretty low for the effort to find it.

### Expected Behaviour

Infinite and not finite 

### Modpack Version

1.1.2

### Screenshots

![IMG_1344](https://github.com/user-attachments/assets/3b870880-102c-46ef-ae15-c7c78145072a)

**Comment by Gogo08190** [comment]
Not a bug. 

This is intentional for custom veins.
