### ISSUE TITLE
[BUG] CobbleGenRandomizer not working

### ISSUE THREAD

**Issue by ChimeraGaming** [Gogo08190/chroma-endless-2#46]
### Description of the Bug

https://www.curseforge.com/minecraft/mc-mods/cobblegenrandomizer

Tested in creative after being on a server, confirmed the config file is not even in the pack, The .toml file just has comments (#) no actual code.

10 minutes of these creative gens running and not a single custom gen from this mod.

Thank you!

### Expected Behaviour

Gens working

### Modpack Version

1.1.3

### Screenshots

![2024-09-23_14 04 41](https://github.com/user-attachments/assets/752725e5-da0b-4838-a3c5-fd9e1d449457)
![image](https://github.com/user-attachments/assets/74d3ba83-0d84-4051-99bf-8a11c313f88d)

### Extra Info

https://www.curseforge.com/minecraft/mc-mods/cobblegenrandomizer

**Comment by Gogo08190** [comment]
You don't respect the position of the lava and water. They work very well

**Comment by ChimeraGaming** [comment]
Can you explain this some more? If we think of the setup in a 5x5 with 1 being left and a being top. The image shows that if water and lava run into each other with a sandstone under it, it'll make sandstone.

I've tried having the water closer but it makes the lava obsidian.
The setup on the right has sandstone on every place possible without removing the water or lava.

Thanks for the insight.

**Comment by Gogo08190** [comment]
All you have to do is follow what JEI shows you.
On the screen you sent, the water should be on the side and the lava on top.

**Comment by Gogo08190** [comment]
![2024-09-24_18 36 43](https://github.com/user-attachments/assets/d9f4abc7-10db-433e-9f48-54172fa25f30)

Like this

**Comment by ChimeraGaming** [comment]
Thank you -.- I don't know why I didn't put the lava up top
