### ISSUE TITLE
[SUGGESTION] Explorer's Compass - Add

### ISSUE THREAD

**Issue by ChimeraGaming** [Gogo08190/chroma-endless-2#47]
### Description of Suggestion

https://www.curseforge.com/minecraft/mc-mods/explorers-compass

### How does this improve the experience?

With all the new structures in the game it would be very handy to have this.
Plus Cartographer is broken and crashes the server when he levels up ( and no new trades).

**Comment by Gogo08190** [comment]
You can use mana and artifice it's the same as explorer compass
Watch from 20:00

https://youtu.be/_U4P3tJS_DY?si=VNjc9-wFl5uXDd6V
