### ISSUE TITLE
[BUG] Can't get any level of Mystical Agriculture Farmland

### ISSUE THREAD

**Issue by ChimeraGaming** [Gogo08190/chroma-endless-2#49]
### Description of the Bug

As shown in images, you should be able to botany mystical seeds, I have used all available soil from dirt, farmland, rich soil, rich farmland, pyro, etc. Everything you can use for seeds and it says this (image 1)
Image 2 shows it should be possible
Image 3 shows that to make these 6 farmland (shown in image 2) you need the Fertilized essence...

To get the essence you need to farm the seeds. I'm at 5 Stacks of ice essence and no fertilized essence (image 4)

It's supposed to be a 10% chance but i'm well past that

### Expected Behaviour

be able to get the fertilized essence to automate mystical seeds

### Modpack Version

1.1.3

### Screenshots

![image](https://github.com/user-attachments/assets/dbb26cb7-fe14-4f12-9937-7f4b07bb8a0a)
![image](https://github.com/user-attachments/assets/1eb95ba9-51e0-45c3-b583-d105b603befd)
![image](https://github.com/user-attachments/assets/331973ee-9aa9-49ec-95e8-04f8ce936ce3)
![image](https://github.com/user-attachments/assets/fd254110-bc96-4c49-b94e-7e16311eefd2)

**Comment by Gogo08190** [comment]
Its possible : https://youtu.be/HJWyjyKdteQ?si=MfR_SsfkMRCIW-v2
