### ISSUE TITLE
[BUG] Flickering when holding specifice items in inventory, when looking at recipe and in the menu 

### ISSUE THREAD

**Issue by leonmcfly** [Gogo08190/chroma-endless-2#5]
### Description of the Bug

https://www.reddit.com/r/feedthebeast/comments/1agljef/weird_flickering_in_inventory_when_holding/
posted it also on the ftb subreddit, because i cant really find the problem 
other mods i installed where Rubidium, Rubidium extra and TexTrues Rubidium Options 
the links for the mods are in the post on subreddit and on the subbredit there is a video on the behavior couldnt upload the video to github 

### Expected Behaviour

open menu 
or 
open inventory hold specific item with mouse 
or 
look at any recipe 

### Modpack Version

1.0.8

**Comment by leonmcfly** [comment]
ok found the problem it was rubidium does anyone have an alternative for rubidium wanna play it but my ryzen 7 5800H with an RTX 3070 Laptop GPU with 2x8GB of ram isnt enough for the game without it

**Comment by hugoduterque** [comment]
Use Embeddium, Embeddium++ and TexTrue's Embeddium Options how it's noted in the subredit

**Comment by Gogo08190** [comment]
Use Embeddium, Embeddium++ and TexTrue's Embeddium Options how it's noted in the subredit
