### ISSUE TITLE
[BUG] Shard of creativity not craftable

### ISSUE THREAD

**Issue by MrPYF** [Gogo08190/chroma-endless-2#51]
### Description of the Bug

The Shard of Creativity is not craftable

### Expected Behaviour

When trying to see the recipe of the Shard of Creativity nothing shows up.
Neither clicking or it or using "R" to view the craft.

### Modpack Version

1.1.3

**Comment by Gogo08190** [comment]
Look at the challenge quests (The millionnaire)
