### ISSUE TITLE
[SUGGESTION] Adding a automatic salvaging table

### ISSUE THREAD

**Issue by iglee42** [Gogo08190/chroma-endless-2#9]
### Description of Suggestion

I could be cool that you add a automatic salvaging table with multiblocked.
It can allow to make the work of the salvaging table from Apotheosis but automaticly

### How does this improve the experience?

It can be very cool, because endermen drops good stuff and you are forced to salvage stuff manually but enderman farms drop too stuff.

**Comment by Gogo08190** [comment]
This will be operational for the next update.
#15
